services:
  app:
    image: mcr.microsoft.com/devcontainers/base:debian-12

    volumes:
      - ..:/workspace:cached

    init: true

    command: sleep infinity

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-touhou}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mynewpassword}
      POSTGRES_DB: ${POSTGRES_DB:-touhou}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
volumes:
  db_data:
